resources:
  - name: maven_project
    type: GitRepo
    configuration:
      gitProvider: vijay_github
      path: vijayreddy1991/docker
      sha: 
      
  - name: mvn_Build
    type: BuildInfo
    configuration:
      sourceArtifactory: vijay_artifactory
      buildNumber: 1
      buildName: mvntest

pipelines:
  - name: pipeline_mvn
    steps:
      - name: mavenBuild
        type: MvnBuild
        configuration:
          sourceLocation: ./artifactory-maven-plugin-example
          mvnCommand: clean install -f ./pom.xml
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: maven_project
          integrations:
            - name: vijay_artifactory
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
                options: ""
        execution:
          onStart:
            - apt install default-jdk
            - pushd /tmp 
            - wget http://mirrors.estointernet.in/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
            - tar xzvf apache-maven-3.6.1-bin.tar.gz
            - 'export PATH=$PATH:/tmp/apache-maven-3.6.1/bin'
            - export M2_HOME=/tmp/apache-maven-3.6.1/
            - popd
            - java -version
            - mvn --version
          onSuccess:
            - echo "success"

      - name: maven_publish
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: mavenBuild
          outputResources:
            - name: maven_Build
        execution:
          onSuccess:
            - echo "success"
